force-app/main/default/objects/ChatGPT_Integration__mdt/ChatGPT_Integration__mdt.object-meta.xml
<CustomObject>
    <label>ChatGPT Integration</label>
    <pluralLabel>ChatGPT Integrations</pluralLabel>
</CustomObject>

force-app/main/default/objects/ChatGPT_Integration__mdt/fields/Authorization__c.field-meta.xml
<CustomField>
    <fullName>Authorization__c</fullName>
    <label>Authorization</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ChatGPT_Integration__mdt/fields/OrgId__c.field-meta.xml
<CustomField>
    <fullName>OrgId__c</fullName>
    <label>OrgId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VR_Util.cls
public without sharing class VR_Util {
    
    public static VR_Util createInstance(){
        return new VR_Util();
    }
    
    public ChatGPT_Integration__mdt getChatGptIntegrationRecord(String developerName){
        ChatGPT_Integration__mdt chatGpt;
        List<ChatGPT_Integration__mdt> mDList = [SELECT Id, DeveloperName, MasterLabel, OrgId__c, Authorization__c 
        FROM ChatGPT_Integration__mdt 
        WHERE DeveloperName =: developerName 
        LIMIT 1];

        if(!mdList.isEmpty()){
            chatGpt = mDList[0];
        }

        return chatGpt;
    }
}